# vim: set fileencoding=utf-8
"""
org/acmsl/artifact/licdata/application/licdata_artifact_app.py

This script defines the LicdataArtifactApp class.

Copyright (C) 2024-today acmsl's licdata-artifact

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
import asyncio
from pythoneda.shared.application import enable, PythonEDA
from org.acmsl.artifact.licdata.domain import LicdataArtifact
from org.acmsl.artifact.licdata.infrastructure.dbus import (
    LicdataArtifactDbusSignalListener,
)
from typing import Dict


@enable(LicdataArtifactDbusSignalListener)
class LicdataArtifactApp(PythonEDA):
    """
    Licdata Artifact Application.

    Class name: LicdataArtifactApp

    Responsibilities:
        - Define the Licdata Artifact application.

    Collaborators:
        - None
    """

    def __init__(self):
        """
        Creates a new LicdataArtifactApp instance.
        """
        # licdata_artifact_banner is automatically generated by the Nix flake.
        try:
            from org.acmsl.artifact.licdata.application.licdata_artifact_banner import (
                LicdataArtifactBanner,
            )

            banner = LicdataArtifactBanner()
        except ImportError:
            banner = None

        super().__init__(banner, __file__)


if __name__ == "__main__":
    asyncio.run(
        LicdataArtifactApp.main(
            "org.acmsl.artifact.icdata.application.LicdataArtifactApp"
        )
    )
# vim: syntax=python ts=4 sw=4 sts=4 tw=79 sr et
# Local Variables:
# mode: python
# python-indent-offset: 4
# tab-width: 4
# indent-tabs-mode: nil
# fill-column: 79
# End:
